# Generated by Django 4.0.5 on 2022-07-14 09:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='mota',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='noidung',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='extrawork',
            name='mota',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='mota',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='samplestep',
            name='mota',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/%y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diachi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sodienthoai',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='mota',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
