# Generated by Django 4.0.5 on 2022-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdata', '0002_alter_categorys_mota_alter_comment_noidung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='part',
        ),
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.ManyToManyField(default=None, null=True, to='erpdata.part'),
        ),
    ]
