# Generated by Django 4.0.5 on 2022-07-15 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpdata', '0003_remove_user_part_user_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembase',
            name='idnhanvienthamgia',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='idbophanthamgiaduan',
            field=models.ManyToManyField(null=True, to='erpdata.part'),
        ),
    ]
